# Generated by Django 3.0.4 on 2020-03-20 18:27

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('psite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
